name: Build and Push Dockerfile to Dockerhub
on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths: 
      - 'Dockerfile'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dsci-310-group-17:latest
        
    - name: Login to DockerHub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Tag Docker Image
      run: docker tag dsci-310-group-17:latest erliuu/dsci-310-group-17:latest
    
    - name: Push to DockerHub
      run: docker push erliuu/dsci-310-group-17:latest
